/* generated by neuraltransistor -- boot harness for "valence"
 *
 * Runs the circuit for 64 ticks against a fixed input and folds every spike
 * into an FNV-1a digest, then prints it. The expected digest was computed from the
 * numpy reference at emit time, so a matching line proves this cross-compiled ARM
 * build computed bit-identical spikes -- not merely that it booted.
 */
#include <stdint.h>
#include "valence.h"

/* ARM semihosting: the emulator's console. bkpt 0xAB traps to the host. */
static int semihost(int op, void *arg) {
    register int r0 __asm__("r0") = op;
    register void *r1 __asm__("r1") = arg;
    __asm__ volatile("bkpt 0xAB" : "+r"(r0) : "r"(r1) : "memory");
    return r0;
}
static void puts_(const char *s) { semihost(0x04 /* SYS_WRITE0 */, (void *)s); }

static void put_hex64(uint64_t v, char *out) {
    static const char D[] = "0123456789abcdef";
    for (int i = 0; i < 16; ++i) out[15 - i] = D[(v >> (4 * i)) & 0xF];
    out[16] = 0;
}

static valence_state_t st;
static int16_t drive[VALENCE_N_NEURONS];

int main(void) {
    puts_("neuraltransistor valence\n");

    for (int i = 0; i < VALENCE_N_NEURONS; ++i)
        drive[i] = (int16_t)(((i * 37) % 400) - 100);

    valence_reset(&st);

    uint64_t h = 0xCBF29CE484222325ULL;
    uint32_t spikes = 0;
    for (int t = 0; t < 64; ++t) {
        valence_tick(&st, drive);
        for (int i = 0; i < VALENCE_N_NEURONS; ++i) {
            h ^= (uint64_t)st.fired[i];
            h *= 0x100000001B3ULL;
            spikes += st.fired[i];
        }
    }

    char buf[24];
    put_hex64(h, buf);
    puts_("DIGEST ");
    puts_(buf);
    puts_("\n");

    put_hex64((uint64_t)spikes, buf);
    puts_("SPIKES ");
    puts_(buf + 8);          /* spikes fit comfortably in 32 bits */
    puts_("\n");

    /* SYS_EXIT(ApplicationExit) so the emulator returns instead of spinning */
    int args[2] = {0x20026, 0};
    semihost(0x18, args);
    for (;;) { }
    return 0;
}
