/* generated by neuraltransistor -- startup for "valence"
 *
 * Reset entry for Cortex-M. The vector table's first word is the initial stack
 * pointer and the second is the reset vector; the core loads both in hardware
 * before executing anything, which is why this table must be at the start of flash.
 *
 * .data is copied out of flash into SRAM and .bss is zeroed here. Skipping that is
 * the classic bare-metal bug that works anyway in an emulator -- which starts RAM
 * zeroed -- and then fails on silicon, which does not.
 */
#include <stdint.h>

extern int main(void);

extern uint32_t _sidata, _sdata, _edata, _sbss, _ebss, _stack_top;

void reset_handler(void) {
    uint32_t *src = &_sidata, *dst = &_sdata;
    while (dst < &_edata) *dst++ = *src++;
    for (dst = &_sbss; dst < &_ebss; ) *dst++ = 0u;
    main();
    for (;;) { }
}

static void hang(void) { for (;;) { } }

__attribute__((section(".vectors"), used))
void (*const vectors[])(void) = {
    (void (*)(void))(&_stack_top),   /* initial SP  */
    reset_handler,                   /* reset       */
    hang,                            /* NMI         */
    hang,                            /* HardFault   */
    hang, hang, hang, 0, 0, 0, 0,    /* MM/Bus/Usage, reserved */
    hang,                            /* SVC         */
    0, 0,
    hang,                            /* PendSV      */
    hang,                            /* SysTick     */
};
