/* generated by neuraltransistor -- circuit "valence" */
#ifndef VALENCE_H
#define VALENCE_H
#include <stdint.h>

#define VALENCE_N_NEURONS 429
#define VALENCE_N_EDGES   1932
#define VALENCE_N_MOD     8442
#define VALENCE_DT_US     500
#define VALENCE_WEIGHT_BITS 8

/* Mutable state. This is the only RAM the circuit needs. */
typedef struct {
    int16_t v[429];        /* membrane potential, Q8.8 */
    uint8_t fired[429];    /* spike output of the last tick */
    uint8_t refrac[429];   /* ticks remaining in refractory */
    uint8_t gain[429];  /* modulatory gain, Q0.8, 255 = unity */
} valence_state_t;

void valence_reset(valence_state_t *s);
/* Advance one tick. `input` is Q8.8 current injected per neuron, or NULL. */
void valence_tick(valence_state_t *s, const int16_t *input);

#endif
