/* generated by neuraltransistor -- runtime for "valence" */
#include "valence.h"

extern const uint16_t valence_indptr[];
extern const uint16_t valence_index[];
extern const uint8_t valence_code[];
extern const int16_t valence_book[];
extern const int8_t  valence_sign[];
extern const uint16_t valence_decay_q8[];
extern const int16_t valence_thresh[];
extern const uint16_t valence_mod_pre[];
extern const uint16_t valence_mod_post[];
extern const uint8_t valence_mod_w[];
#define N VALENCE_N_NEURONS

static int32_t acc_buf[N];

/* open-coded byte fill: this runtime pulls in no libc, not even a header */
static void valence_fill8(uint8_t *d, uint8_t v, uint32_t n) {
    while (n--) *d++ = v;
}

void valence_reset(valence_state_t *s) {
    valence_fill8((uint8_t *)s, 0, sizeof(*s));
    valence_fill8(s->gain, 128, sizeof(s->gain));
}

void valence_tick(valence_state_t *s, const int16_t *input) {
    for (uint32_t i = 0; i < N; ++i) acc_buf[i] = 0;

    /* Event-driven propagation. Only neurons that fired last tick walk
     * their row, and Dale's law means the sign is constant across that row,
     * so the +-1 never enters the inner loop. */
    for (uint32_t i = 0; i < N; ++i) {
        if (!s->fired[i]) continue;
        const int32_t sg = (int32_t)valence_sign[i];
        const uint32_t a = valence_indptr[i], b = valence_indptr[i + 1];
        for (uint32_t k = a; k < b; ++k) {
            acc_buf[valence_index[k]] += sg * (int32_t)valence_book[valence_code[k]];
        }
    }

/* Modulatory pass: dopaminergic/octopaminergic terminals SCALE their
 * target's gain rather than injecting current. Additive compilation of
 * these edges is the single most common way to lose gating behaviour. */
for (uint32_t k = 0; k < 8442u; ++k) {
    if (!s->fired[valence_mod_pre[k]]) continue;
    uint32_t t = valence_mod_post[k];
    int32_t g = (int32_t)s->gain[t] + (int32_t)valence_mod_w[k];
    s->gain[t] = (uint8_t)(g > 255 ? 255 : g);
}

    for (uint32_t i = 0; i < N; ++i) {
        int32_t acc = acc_buf[i];
        if (input) acc += (int32_t)input[i];
        acc = (acc * (int32_t)s->gain[i]) >> 8;
        if (s->refrac[i]) { s->refrac[i]--; s->v[i] = 0; s->fired[i] = 0; continue; }
        int32_t v = ((int32_t)s->v[i] * (int32_t)valence_decay_q8[i]) >> 8;
        v += acc;
        if (v >  32767) v =  32767;
        if (v < -32768) v = -32768;
        if (v >= (int32_t)valence_thresh[i]) {
            s->fired[i] = 1; s->v[i] = 0; s->refrac[i] = 4;
        } else {
            s->fired[i] = 0; s->v[i] = (int16_t)v;
        }
    }

    /* gain relaxes back toward unity so modulation is transient */
    for (uint32_t i = 0; i < N; ++i) {
        int32_t g = (int32_t)s->gain[i];
        s->gain[i] = (uint8_t)(g + ((128 - g) >> 5));
    }
}
